name: flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.21.2
  freezed_annotation: ^3.1.0
  go_router: ^16.0.0
  hooks_riverpod: ^2.6.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_serializable: ^6.9.5
  photo_view: ^0.15.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  webview_flutter: ^4.13.0

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/
